spring:
    application:
        name: authentication-service
    data:
        mongodb:
            host: localhost
            port: 27017
            database: users_db
            #username: root
            #password: root
            auto-index-creation: true
        redis:
            host: redis_db
            port: 6380

    mail:
        host: smtp.gmail.com
        port: 587
        username: slava.gusarov.73@mail.ru #вставить свою почту
        password:
        protocol: smtp
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

jwt:
    access-token-expire-time-ms: 3600
    refresh-token-expire-time-ms: 2592000
    refresh-token-name: refresh-token

rsa:
    private-key: classpath:certs/private.pem
    public-key: classpath:certs/public.pem

application:
    unverified_user_expire_time_seconds: 3600

