spring:
    application:
        name: authentication-service
    mail:
        username: slava.gusarov.73@mail.ru
    data:
        mongodb:
            host: localhost
            port: 27018
            authentication-database: admin
            database: users_db
            username: root
            password: root
        redis:
            host: localhost
            port: 6380

jwt:
    access-token-expire-time-ms: 3600
    refresh-token-expire-time-ms: 2592000
    refresh-token-name: refresh-token

rsa:
    private-key: classpath:certs/private.pem
    public-key: classpath:certs/public.pem

application:
    unverified_user_expire_time_seconds: 3600

