version: '3.8'
services:
  redisdb:
    image: redis:7.2.1
    container_name: redis_db
    restart: always
    ports:
      - '6380:6379'
    volumes:
      - redis_data:/data
    networks:
      - my_network

  users_db:
    image: mongo:7.0.2
    container_name: users_db
    restart: always
    ports:
      - '27017:27017'
    #volumes:
    #  - mongodb_data:/data
    networks:
      - my_network

volumes:
  redis_data:
    driver: local
  mongodb_data:
    driver: local

networks:
  my_network:
    driver: bridge